console.log("running")
function number1 (){
let num = document.getElementById('integer').value;
for (let index = 1; index < 25; index++)
document.getElementById('digit1').innerText += num+index;}


// 1  Question
// let sum = o;
// for (let index = 1; index < 20; index++) {
//     sum+=index;
//     console.log(sum);}


// 2 Question
// let num = 1.5;
// for (let index = 1; index < 26; index++)
//     {console.log(num*index);}

// 3  Question
// let sum = 3.6;
// for (let index = 5; index < 35; index+=5) 
// {console.log(sum*index);}


